/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YangiliklarRouteImport } from './routes/yangiliklar'
import { Route as TopshiriqlarRouteImport } from './routes/topshiriqlar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SaytRouteImport } from './routes/sayt'
import { Route as MualliflarRouteImport } from './routes/mualliflar'
import { Route as MateriallarRouteImport } from './routes/materiallar'
import { Route as AdabiyotRouteImport } from './routes/adabiyot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YangiliklarIdRouteImport } from './routes/yangiliklar.$id'
import { Route as MualliflarSlugRouteImport } from './routes/mualliflar.$slug'

const YangiliklarRoute = YangiliklarRouteImport.update({
  id: '/yangiliklar',
  path: '/yangiliklar',
  getParentRoute: () => rootRouteImport,
} as any)
const TopshiriqlarRoute = TopshiriqlarRouteImport.update({
  id: '/topshiriqlar',
  path: '/topshiriqlar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SaytRoute = SaytRouteImport.update({
  id: '/sayt',
  path: '/sayt',
  getParentRoute: () => rootRouteImport,
} as any)
const MualliflarRoute = MualliflarRouteImport.update({
  id: '/mualliflar',
  path: '/mualliflar',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriallarRoute = MateriallarRouteImport.update({
  id: '/materiallar',
  path: '/materiallar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdabiyotRoute = AdabiyotRouteImport.update({
  id: '/adabiyot',
  path: '/adabiyot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YangiliklarIdRoute = YangiliklarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => YangiliklarRoute,
} as any)
const MualliflarSlugRoute = MualliflarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MualliflarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adabiyot': typeof AdabiyotRoute
  '/materiallar': typeof MateriallarRoute
  '/mualliflar': typeof MualliflarRouteWithChildren
  '/sayt': typeof SaytRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topshiriqlar': typeof TopshiriqlarRoute
  '/yangiliklar': typeof YangiliklarRouteWithChildren
  '/mualliflar/$slug': typeof MualliflarSlugRoute
  '/yangiliklar/$id': typeof YangiliklarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adabiyot': typeof AdabiyotRoute
  '/materiallar': typeof MateriallarRoute
  '/mualliflar': typeof MualliflarRouteWithChildren
  '/sayt': typeof SaytRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topshiriqlar': typeof TopshiriqlarRoute
  '/yangiliklar': typeof YangiliklarRouteWithChildren
  '/mualliflar/$slug': typeof MualliflarSlugRoute
  '/yangiliklar/$id': typeof YangiliklarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adabiyot': typeof AdabiyotRoute
  '/materiallar': typeof MateriallarRoute
  '/mualliflar': typeof MualliflarRouteWithChildren
  '/sayt': typeof SaytRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topshiriqlar': typeof TopshiriqlarRoute
  '/yangiliklar': typeof YangiliklarRouteWithChildren
  '/mualliflar/$slug': typeof MualliflarSlugRoute
  '/yangiliklar/$id': typeof YangiliklarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adabiyot'
    | '/materiallar'
    | '/mualliflar'
    | '/sayt'
    | '/sitemap.xml'
    | '/topshiriqlar'
    | '/yangiliklar'
    | '/mualliflar/$slug'
    | '/yangiliklar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adabiyot'
    | '/materiallar'
    | '/mualliflar'
    | '/sayt'
    | '/sitemap.xml'
    | '/topshiriqlar'
    | '/yangiliklar'
    | '/mualliflar/$slug'
    | '/yangiliklar/$id'
  id:
    | '__root__'
    | '/'
    | '/adabiyot'
    | '/materiallar'
    | '/mualliflar'
    | '/sayt'
    | '/sitemap.xml'
    | '/topshiriqlar'
    | '/yangiliklar'
    | '/mualliflar/$slug'
    | '/yangiliklar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdabiyotRoute: typeof AdabiyotRoute
  MateriallarRoute: typeof MateriallarRoute
  MualliflarRoute: typeof MualliflarRouteWithChildren
  SaytRoute: typeof SaytRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopshiriqlarRoute: typeof TopshiriqlarRoute
  YangiliklarRoute: typeof YangiliklarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yangiliklar': {
      id: '/yangiliklar'
      path: '/yangiliklar'
      fullPath: '/yangiliklar'
      preLoaderRoute: typeof YangiliklarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topshiriqlar': {
      id: '/topshiriqlar'
      path: '/topshiriqlar'
      fullPath: '/topshiriqlar'
      preLoaderRoute: typeof TopshiriqlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sayt': {
      id: '/sayt'
      path: '/sayt'
      fullPath: '/sayt'
      preLoaderRoute: typeof SaytRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mualliflar': {
      id: '/mualliflar'
      path: '/mualliflar'
      fullPath: '/mualliflar'
      preLoaderRoute: typeof MualliflarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiallar': {
      id: '/materiallar'
      path: '/materiallar'
      fullPath: '/materiallar'
      preLoaderRoute: typeof MateriallarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adabiyot': {
      id: '/adabiyot'
      path: '/adabiyot'
      fullPath: '/adabiyot'
      preLoaderRoute: typeof AdabiyotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yangiliklar/$id': {
      id: '/yangiliklar/$id'
      path: '/$id'
      fullPath: '/yangiliklar/$id'
      preLoaderRoute: typeof YangiliklarIdRouteImport
      parentRoute: typeof YangiliklarRoute
    }
    '/mualliflar/$slug': {
      id: '/mualliflar/$slug'
      path: '/$slug'
      fullPath: '/mualliflar/$slug'
      preLoaderRoute: typeof MualliflarSlugRouteImport
      parentRoute: typeof MualliflarRoute
    }
  }
}

interface MualliflarRouteChildren {
  MualliflarSlugRoute: typeof MualliflarSlugRoute
}

const MualliflarRouteChildren: MualliflarRouteChildren = {
  MualliflarSlugRoute: MualliflarSlugRoute,
}

const MualliflarRouteWithChildren = MualliflarRoute._addFileChildren(
  MualliflarRouteChildren,
)

interface YangiliklarRouteChildren {
  YangiliklarIdRoute: typeof YangiliklarIdRoute
}

const YangiliklarRouteChildren: YangiliklarRouteChildren = {
  YangiliklarIdRoute: YangiliklarIdRoute,
}

const YangiliklarRouteWithChildren = YangiliklarRoute._addFileChildren(
  YangiliklarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdabiyotRoute: AdabiyotRoute,
  MateriallarRoute: MateriallarRoute,
  MualliflarRoute: MualliflarRouteWithChildren,
  SaytRoute: SaytRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopshiriqlarRoute: TopshiriqlarRoute,
  YangiliklarRoute: YangiliklarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './routes.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
